import React, { useState } from 'react';
import { 
  CheckCircle2, 
  Clock, 
  Calendar, 
  Building2, 
  Users, 
  Share2, 
  Copy, 
  Check, 
  Download, 
  Sparkles, 
  ArrowRight, 
  PlusCircle, 
  ShieldCheck, 
  TrendingDown, 
  HeartHandshake, 
  BookOpen, 
  Award 
} from 'lucide-react';
import { CommunityActionAnalysis, ActionInstructionStep } from '../cleanAirData';
import { PledgeItem } from '../App';

interface CommunityActionAnalysisCardProps {
  pledge: PledgeItem;
  analysis: CommunityActionAnalysis;
  locationName: string;
  onResetOrNewPledge: () => void;
}

export const CommunityActionAnalysisCard: React.FC<CommunityActionAnalysisCardProps> = ({
  pledge,
  analysis,
  locationName,
  onResetOrNewPledge,
}) => {
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [completedChecklist, setCompletedChecklist] = useState<string[]>([]);
  const [copiedPlan, setCopiedPlan] = useState(false);
  const [activeStepTab, setActiveStepTab] = useState<number>(1);

  const toggleChecklistItem = (itemText: string) => {
    setCompletedChecklist(prev => 
      prev.includes(itemText) ? prev.filter(t => t !== itemText) : [...prev, itemText]
    );
  };

  const handleCopyFullPlan = () => {
    const markdownPlan = `### Community Clean Air Action Plan for ${pledge.name}
**Location**: ${locationName}
**Category**: ${pledge.category} (${pledge.impact})
**My Pledge**: "${pledge.pledge}"

#### Impact Analysis:
- **Summary**: ${analysis.summaryAnalysis}
- **Emissions Cut**: ${analysis.keyEmissionsCut}
- **Health Benefit**: ${analysis.localHealthBenefit}

#### Step 1: ${analysis.steps[0]?.timeframe} - ${analysis.steps[0]?.title}
- **Instruction**: ${analysis.steps[0]?.instruction}
- **Concrete Deliverable**: ${analysis.steps[0]?.concreteDeliverable}
- **Action Checklist**:
${analysis.steps[0]?.checklistItems.map(item => `  - [ ] ${item}`).join('\n')}

#### Step 2: ${analysis.steps[1]?.timeframe} - ${analysis.steps[1]?.title}
- **Instruction**: ${analysis.steps[1]?.instruction}
- **Concrete Deliverable**: ${analysis.steps[1]?.concreteDeliverable}
- **Action Checklist**:
${analysis.steps[1]?.checklistItems.map(item => `  - [ ] ${item}`).join('\n')}

#### Step 3: ${analysis.steps[2]?.timeframe} - ${analysis.steps[2]?.title}
- **Instruction**: ${analysis.steps[2]?.instruction}
- **Concrete Deliverable**: ${analysis.steps[2]?.concreteDeliverable}
- **Action Checklist**:
${analysis.steps[2]?.checklistItems.map(item => `  - [ ] ${item}`).join('\n')}

*Generated by SDG 13 Global Air Quality Explorer & Cloud Firestore Pledge Tracker*`;

    navigator.clipboard.writeText(markdownPlan);
    setCopiedPlan(true);
    setTimeout(() => setCopiedPlan(false), 2500);
  };

  const handleDownloadPlan = () => {
    const textPlan = `SDG 13 COMMUNITY CLEAN AIR ACTION PLAN
Participant: ${pledge.name}
Target City: ${locationName}
Category: ${pledge.category} (${pledge.impact})
Pledge: "${pledge.pledge}"
Timestamp: ${pledge.timestamp}

==================================================
1. IMPACT ANALYSIS
==================================================
Summary: ${analysis.summaryAnalysis}
Emissions Cut: ${analysis.keyEmissionsCut}
Health Protection: ${analysis.localHealthBenefit}

==================================================
2. STEP-BY-STEP COMMUNITY EXECUTION ROADMAP
==================================================
${analysis.steps.map(s => `
[STEP ${s.stepNumber}]: ${s.timeframe} - ${s.title}
Action: ${s.instruction}
Deliverable: ${s.concreteDeliverable}
Key Checkpoints:
${s.checklistItems.map(c => `  [*] ${c}`).join('\n')}
Recommended Resource: ${s.suggestedResource}
`).join('\n--------------------------------------------------\n')}

Plan generated via Google Cloud Firestore & SDG 13 Clean Air Initiative.`;

    const blob = new Blob([textPlan], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Clean_Air_Action_Plan_${pledge.name.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const totalChecklistCount = analysis.steps.reduce((acc, s) => acc + s.checklistItems.length, 0);
  const progressPercent = Math.round((completedChecklist.length / Math.max(1, totalChecklistCount)) * 100);

  return (
    <div id="community-action-analysis-card" className="bg-white rounded-xl border-2 border-[#DE6738]/80 shadow-md p-5 space-y-5 text-stone-900 transition-all">
      
      {/* Top Banner: Success confirmation */}
      <div className="bg-gradient-to-r from-[#1B5D77] to-[#13465A] text-white p-4 rounded-lg flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-inner">
        <div className="flex items-start gap-3">
          <div className="w-9 h-9 rounded-full bg-white/20 flex items-center justify-center shrink-0 mt-0.5">
            <CheckCircle2 className="w-5 h-5 text-[#ECC247]" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-bold text-sm tracking-wide">Pledge Saved to Database</span>
              <span className="text-[10px] bg-black/30 text-white px-2 py-0.5 rounded border border-white/20">
                Firestore &bull; /pledges
              </span>
            </div>
            <p className="text-xs text-stone-100 mt-0.5">
              Thank you, <strong className="text-white font-semibold">{pledge.name}</strong>! Your commitment is now live on the global civic tracker.
            </p>
          </div>
        </div>

        <button
          onClick={onResetOrNewPledge}
          className="self-start sm:self-auto px-3 py-1.5 bg-white/10 hover:bg-white/20 border border-white/25 rounded-md text-xs font-medium text-white transition flex items-center gap-1.5 cursor-pointer whitespace-nowrap"
          title="Submit an additional pledge"
        >
          <PlusCircle className="w-3.5 h-3.5" />
          <span>New Pledge</span>
        </button>
      </div>

      {/* Quote of User's Pledge */}
      <div className="bg-[#FDF2EC]/40 border border-[#F5C7B4] rounded-lg p-3.5">
        <div className="flex items-center justify-between gap-2 mb-1.5 flex-wrap">
          <span className="text-[11px] font-semibold text-[#1B5D77] bg-[#E8F3F7] border border-[#B8DEEC] px-2 py-0.5 rounded-full">
            {pledge.category}
          </span>
          <span className="text-[10px] text-stone-500 font-mono">
            {pledge.impact} &bull; {pledge.timestamp}
          </span>
        </div>
        <p className="text-xs text-stone-800 italic leading-relaxed">
          &ldquo;{pledge.pledge}&rdquo;
        </p>
      </div>

      {/* Analysis Headline & Environmental Payoff */}
      <div className="space-y-3 pt-1">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-[#DE6738]" />
          <h3 className="text-sm font-bold text-stone-900">
            Community Action Blueprint & Impact Analysis
          </h3>
        </div>

        <p className="text-xs text-stone-600 leading-relaxed">
          {analysis.summaryAnalysis}
        </p>

        {/* 2 Impact Metric Pills */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 text-xs">
          <div className="bg-[#FDF2EC] border border-[#F5C7B4] rounded-lg p-2.5 flex items-start gap-2.5">
            <TrendingDown className="w-4 h-4 text-[#DE6738] shrink-0 mt-0.5" />
            <div>
              <span className="block font-bold text-stone-900 text-[11px]">Direct Urban Emissions Cut</span>
              <span className="text-[11px] text-[#DE6738] leading-tight block mt-0.5 font-medium">{analysis.keyEmissionsCut}</span>
            </div>
          </div>

          <div className="bg-[#E8F3F7] border border-[#B8DEEC] rounded-lg p-2.5 flex items-start gap-2.5">
            <ShieldCheck className="w-4 h-4 text-[#1B5D77] shrink-0 mt-0.5" />
            <div>
              <span className="block font-bold text-stone-900 text-[11px]">Community Health Shield</span>
              <span className="text-[11px] text-[#1B5D77] leading-tight block mt-0.5 font-medium">{analysis.localHealthBenefit}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Progress Checklist Header */}
      <div className="pt-2 border-t border-stone-200">
        <div className="flex items-center justify-between text-xs mb-2">
          <div className="flex items-center gap-1.5">
            <Award className="w-4 h-4 text-[#DE6738]" />
            <span className="font-bold text-stone-900">Your Action Progress Today</span>
          </div>
          <span className="font-semibold text-[#DE6738] text-xs">
            {completedChecklist.length} of {totalChecklistCount} Tasks Checked ({progressPercent}%)
          </span>
        </div>

        <div className="w-full bg-stone-200 h-2 rounded-full overflow-hidden">
          <div 
            className="bg-[#DE6738] h-full rounded-full transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          ></div>
        </div>
      </div>

      {/* Step Navigation Tabs */}
      <div className="grid grid-cols-3 gap-1.5 bg-stone-100 p-1 rounded-lg">
        {analysis.steps.map((step) => (
          <button
            key={step.stepNumber}
            onClick={() => setActiveStepTab(step.stepNumber)}
            className={`py-1.5 px-2 rounded-md text-xs font-semibold transition flex flex-col sm:flex-row items-center justify-center gap-1 text-center cursor-pointer ${
              activeStepTab === step.stepNumber
                ? 'bg-white text-[#1B5D77] shadow-sm border border-stone-200'
                : 'text-stone-600 hover:text-stone-900 hover:bg-stone-200/60'
            }`}
          >
            <span className={`w-4 h-4 rounded-full text-[10px] flex items-center justify-center font-bold ${
              activeStepTab === step.stepNumber ? 'bg-[#1B5D77] text-white' : 'bg-stone-300 text-stone-700'
            }`}>
              {step.stepNumber}
            </span>
            <span className="truncate text-[11px]">{step.timeframe.split(' ')[0]}</span>
          </button>
        ))}
      </div>

      {/* Active Step Content */}
      {analysis.steps.map((step) => {
        if (step.stepNumber !== activeStepTab) return null;

        return (
          <div key={step.stepNumber} className="border border-stone-200 rounded-lg p-4 bg-stone-50/50 space-y-3 text-xs">
            <div className="flex items-center justify-between gap-2 flex-wrap pb-2 border-b border-stone-200">
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded font-bold bg-[#E8F3F7] text-[#1B5D77] text-[10px] uppercase tracking-wide border border-[#B8DEEC]">
                  Step {step.stepNumber} &bull; {step.timeframe}
                </span>
                <h4 className="font-bold text-stone-900 text-xs sm:text-sm">
                  {step.title}
                </h4>
              </div>
            </div>

            {/* Instruction description */}
            <p className="text-stone-700 leading-relaxed text-xs">
              {step.instruction}
            </p>

            {/* Concrete deliverable callout */}
            <div className="bg-[#FEF9E7] border border-[#F8E49D] rounded-md p-2.5 text-stone-900">
              <span className="font-bold text-[11px] block text-[#977312] mb-0.5">
                Target Concrete Deliverable:
              </span>
              <p className="text-[11px] leading-snug text-stone-700">
                {step.concreteDeliverable}
              </p>
            </div>

            {/* Interactive Checklist items */}
            <div className="space-y-2 pt-1">
              <span className="font-semibold text-stone-800 text-[11px] block">
                Interactive Action Checkpoints:
              </span>
              <div className="space-y-1.5">
                {step.checklistItems.map((item, idx) => {
                  const isChecked = completedChecklist.includes(item);
                  return (
                    <label 
                      key={idx} 
                      className={`flex items-start gap-2.5 p-2 rounded-md border transition cursor-pointer ${
                        isChecked 
                          ? 'bg-[#FDF2EC] border-[#F5C7B4] text-stone-900' 
                          : 'bg-white border-stone-200 text-stone-800 hover:bg-stone-100/60'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => toggleChecklistItem(item)}
                        className="mt-0.5 rounded text-[#DE6738] focus:ring-[#DE6738] w-3.5 h-3.5 cursor-pointer"
                      />
                      <span className={`text-xs leading-tight ${isChecked ? 'line-through opacity-80' : ''}`}>
                        {item}
                      </span>
                    </label>
                  );
                })}
              </div>
            </div>

            {/* Suggested Resource */}
            <div className="pt-2 flex items-center gap-1.5 text-[11px] text-stone-500">
              <BookOpen className="w-3.5 h-3.5 text-stone-400 shrink-0" />
              <span>Recommended Tool / Resource: <strong className="text-stone-700 font-medium">{step.suggestedResource}</strong></span>
            </div>
          </div>
        );
      })}

      {/* Action Toolbar: Share, Copy, Download, New */}
      <div className="pt-2 border-t border-stone-200 flex flex-wrap items-center justify-between gap-2 text-xs">
        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleCopyFullPlan}
            className="px-3 py-1.5 bg-stone-100 hover:bg-stone-200 border border-stone-300 text-stone-700 rounded-md font-medium transition flex items-center gap-1.5 cursor-pointer text-xs"
            title="Copy full markdown action plan"
          >
            {copiedPlan ? <Check className="w-3.5 h-3.5 text-[#1B5D77]" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedPlan ? 'Plan Copied!' : 'Copy Plan'}</span>
          </button>

          <button
            onClick={handleDownloadPlan}
            className="px-3 py-1.5 bg-stone-100 hover:bg-stone-200 border border-stone-300 text-stone-700 rounded-md font-medium transition flex items-center gap-1.5 cursor-pointer text-xs"
            title="Download formatted text plan"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Plan (.txt)</span>
          </button>
        </div>

        <button
          onClick={onResetOrNewPledge}
          className="px-3.5 py-1.5 bg-[#DE6738] hover:bg-[#C4552A] text-white rounded-md font-semibold transition flex items-center gap-1.5 cursor-pointer text-xs ml-auto shadow-sm"
        >
          <span>Submit Another Action</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>

    </div>
  );
};
